-- 授予 zyp 用户对所有表的完整权限
-- 需要使用 postgres 超级用户执行此脚本

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO zyp;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO zyp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO zyp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO zyp;
